<script setup lang="ts">
import { computed } from 'vue'
import { usePlanStore } from '../../stores/planStore'
import { useProgressStore } from '../../stores/progressStore'
import { parsePlanStructure } from '../../composables/useMarkdownParser'
import LearningStep from './LearningStep.vue'
import MarkdownBlocks from './MarkdownBlocks.vue'
import LoadingSpinner from '../ui/LoadingSpinner.vue'

const planStore = usePlanStore()
const progressStore = useProgressStore()

// 数据流一旦收到 SSE 的 Token，将会响应式驱动进行正则划片并自动在页面结构化映射！
const structure = computed(() => parsePlanStructure(planStore.planMarkdown))

// 全局响应进度（0-100）
const currentProgress = computed(() => {
  return progressStore.getTechProgress(planStore.form.techName, structure.value.steps.length)
})

// 处理生成初期：网络延迟导致尚未出现规范大标题时，不能空着白板。给一个骨架态或回显态
const showRaw = computed(() => {
  return planStore.status === 'generating' && 
         !structure.value.intro && 
         structure.value.steps.length === 0 && 
         !structure.value.outro
})

// === 👇 导出脱水内容的特性逻辑 ===
const exportMarkdown = () => {
  const blob = new Blob([planStore.planMarkdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `StudyAgent_${planStore.form.techName.replace(/\s+/g, '_')}_打怪指南.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

const exportHtml = async () => {
  try {
    const { marked } = await import('marked')
    // 采用同步 parse，禁用警告
    const htmlContent = marked.parse(planStore.planMarkdown, { async: false })
    const fullHtml = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <title>${planStore.form.techName} 学习计划</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 2rem; color: #333; }
    pre { background: #1f2428; padding: 1rem; border-radius: 8px; overflow-x: auto; color: #e1e4e8; }
    code { font-family: ui-monospace, monospace; background: #f3f4f6; padding: 0.2rem 0.4rem; border-radius: 4px; color: #d926a9; }
    pre code { background: transparent; padding: 0; color: inherit; }
    h1, h2, h3 { color: #111; margin-top: 2em; border-bottom: 1px solid #eaecef; padding-bottom: .3em; }
    h1 { font-size: 2.2em; }
    a { color: #3b82f6; text-decoration: none; }
    a:hover { text-decoration: underline; }
    blockquote { border-left: 4px solid #dfe2e5; margin: 0; padding: 0 1em; color: #6a737d; }
  </style>
</head>
<body>
  <h1>${planStore.form.techName} 定制学习与实战计划</h1>
  <p><em>Generated by Study Agent & DeepSeek Ai Backend</em></p>
  <hr />
  ${htmlContent}
</body>
</html>`
    const blob = new Blob([fullHtml], { type: 'text/html;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `StudyAgent_${planStore.form.techName.replace(/\s+/g, '_')}_沉浸阅读版.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  } catch (err) {
    console.warn('Failed to export HTML', err)
  }
}
</script>

<template>
  <div class="w-full relative">
    
    <!-- 刚生成时没捕捉到标题时，使用基础显示的消隐过度态 -->
    <div v-if="showRaw" class="animate-pulse bg-white/60 rounded-3xl p-6 shadow-sm border border-gray-100 backdrop-blur">
       <div class="h-4 bg-gray-200 rounded w-1/4 mb-4"></div>
       <div class="h-4 bg-gray-200 rounded w-2/4 mb-4"></div>
       <div class="h-4 bg-gray-200 rounded w-1/3"></div>
       <pre class="whitespace-pre-wrap font-sans text-gray-400 mt-4 max-h-20 px-2 overflow-hidden text-xs">{{ planStore.planMarkdown }}...正在脑补中</pre>
    </div>

    <!-- 结构化魔法卡片展现区 -->
    <div v-else class="space-y-6 lg:space-y-8 animate-fade-in">
      
      <!-- 导语与场景概览 -->
      <div v-if="structure.intro.trim()" class="bg-white rounded-3xl p-6 sm:p-8 shadow-sm border border-gray-100 border-t-brand-500 border-t-4 transition-all">
        <MarkdownBlocks :content="structure.intro" />
      </div>

      <!-- 收缩栈：学习步骤卡片呈现阵列 -->
      <div v-if="structure.steps.length > 0" class="mt-8">
        <!-- 总进度看板区 -->
        <div class="mb-8 p-6 bg-white rounded-3xl shadow-sm border border-gray-100">
           <div class="flex justify-between items-end mb-3">
             <h2 class="text-xl font-bold text-gray-900 flex items-center gap-2">
               <svg class="w-6 h-6 text-brand-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                 <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
               </svg>
               分解动作与实战演练（共 {{ structure.steps.length }} 步）
             </h2>
             <span class="text-2xl font-black text-brand-600 tracking-tighter">{{ currentProgress }}%</span>
           </div>
           
           <div class="h-3 w-full bg-gray-100 rounded-full overflow-hidden">
             <!-- 带渐变的平滑长度响应条 -->
             <div class="h-full bg-gradient-to-r from-brand-400 to-green-400 transition-all duration-1000 ease-out" 
                  :style="{ width: `${currentProgress}%` }">
             </div>
           </div>
           <p v-if="currentProgress === 100" class="text-sm font-bold text-green-600 mt-3 flex items-center gap-1 animate-pulse">
             <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
               <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7" />
             </svg>
             太棒了！你已经完成了本次定制的所有学习挑战！
           </p>
        </div>
        
        <!-- 卡片逐个跌落展开的列表动画！ -->
        <TransitionGroup name="list" tag="div">
          <LearningStep 
            v-for="(step, idx) in structure.steps" 
            :key="idx"
            :index="idx"
            :title="step.title"
            :content="step.content"
          />
        </TransitionGroup>
      </div>

      <!-- 最终代码展示、寄语、配套工具补充区 -->
      <div v-if="structure.outro.trim()" class="bg-white rounded-3xl p-6 sm:p-8 shadow-sm border border-gray-100 transition-all">
        <MarkdownBlocks :content="structure.outro" />
      </div>

      <!-- 成果离线脱水导出工具栏 -->
      <div v-if="planStore.status === 'done'" class="flex justify-center flex-wrap gap-4 mt-8 pt-4 pb-8 transition-all animate-fade-in">
         <button @click="exportMarkdown" class="flex items-center gap-2 px-6 py-3 bg-white border border-gray-200 text-gray-700 rounded-2xl hover:bg-gray-50 focus:outline-none focus:ring-2 hover:border-brand-300 focus:ring-brand-100 transition-all shadow-sm">
           <svg class="w-5 h-5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
           </svg>
           <span class="font-bold">导出纯净 Markdown</span>
         </button>
         <button @click="exportHtml" class="flex items-center gap-2 px-6 py-3 bg-white border border-gray-200 text-gray-700 rounded-2xl hover:bg-brand-50 group focus:outline-none focus:ring-2 hover:border-brand-300 focus:ring-brand-100 transition-all shadow-sm">
           <svg class="w-5 h-5 text-gray-400 group-hover:text-brand-500 transition-colors" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
           </svg>
           <span class="font-bold group-hover:text-brand-700 transition-colors">导出独立单页 HTML</span>
         </button>
      </div>

    </div>

    <!-- 推送心跳动画针在底部打标 -->
    <div v-if="planStore.status === 'generating'" class="mt-4 flex items-center justify-center p-2 text-brand-500 absolute -bottom-10 left-1/2 -translate-x-1/2">
       <LoadingSpinner />
    </div>
  </div>
</template>

<style scoped>
.list-enter-active,
.list-leave-active {
  transition: all 0.5s cubic-bezier(0.4, 0, 0.2, 1);
}
.list-enter-from,
.list-leave-to {
  opacity: 0;
  transform: translateY(20px) scale(0.98);
}
</style>
